# Generated by cucumber-sinatra. (2014-12-31 13:33:28 +0000)

ENV['RACK_ENV'] = 'test'
ENV['USERNAME'] = 'foo'
ENV['PASSWORD'] = 'bar'
ENV['DYNAMIC_HOST'] = 'dynamic.example.org'
ENV['CF_USERNAME'] = 'derp@derp.org'
ENV['CF_TOKEN'] = 'fdsafgfadsgfdsgfds'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/dynamic_cloudflare.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

require 'cucumber/api_steps'

Capybara.app = DynamicCloudflare

class DynamicCloudflareWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers

  def app
    DynamicCloudflare
  end
end

World do
  DynamicCloudflareWorld.new
end
